# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rampart < Formula
  desc "Audit and enforce GitHub branch protection rules across repos"
  homepage "https://github.com/wdm0006/rampart"
  license "MIT"

  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wdm0006/rampart/releases/download/v0.8.1/rampart_0.8.1_darwin_amd64.tar.gz"
      sha256 "a5f18bae07fc52de77ac677f998e3cbef79b2b4b3c61f83490da02e9e57bd15c"

      define_method(:install) do
        bin.install "rampart"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wdm0006/rampart/releases/download/v0.8.1/rampart_0.8.1_darwin_arm64.tar.gz"
      sha256 "9e38ce97c5d359ac6613896ece5cd0e715b9728331a1d56188bbff6ce8508f58"

      define_method(:install) do
        bin.install "rampart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wdm0006/rampart/releases/download/v0.8.1/rampart_0.8.1_linux_amd64.tar.gz"
      sha256 "94e7fa17510f88d370f3ee1c6533168a27be8a18db5193b5af6ab0cfa5df5bd9"
      define_method(:install) do
        bin.install "rampart"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wdm0006/rampart/releases/download/v0.8.1/rampart_0.8.1_linux_arm64.tar.gz"
      sha256 "3249c0b26e421fbb75939dee4e7a13ea81b41458989091f6567bd8751e5d8c82"
      define_method(:install) do
        bin.install "rampart"
      end
    end
  end

  test do
    system "#{bin}/rampart", "--help"
  end
end
