# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vanity < Formula
  desc "Sync your GitHub contribution graph across multiple accounts"
  homepage "https://github.com/wdm0006/vanity"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wdm0006/vanity/releases/download/v0.1.0/vanity_0.1.0_darwin_amd64.tar.gz"
      sha256 "bfe6a39c0d4034d47bf58449caed552f0d01e96f93407e9e50d60700049c70dd"

      def install
        bin.install "vanity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wdm0006/vanity/releases/download/v0.1.0/vanity_0.1.0_darwin_arm64.tar.gz"
      sha256 "79f3f975ec958ddab564f8fb3a564e019bd3dfd8a707031dcafa3d27b6993876"

      def install
        bin.install "vanity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wdm0006/vanity/releases/download/v0.1.0/vanity_0.1.0_linux_amd64.tar.gz"
      sha256 "6043e4729470c8bfb4f0612853359d0436687b7affc2679cb99f17b3af2332eb"
      def install
        bin.install "vanity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wdm0006/vanity/releases/download/v0.1.0/vanity_0.1.0_linux_arm64.tar.gz"
      sha256 "22481edbc901972bb9bb152a0609f7a841f57de96d6ce0989f332ba13a609097"
      def install
        bin.install "vanity"
      end
    end
  end

  test do
    system "#{bin}/vanity", "--help"
  end
end
