# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vanity < Formula
  desc "Sync your GitHub contribution graph across multiple accounts"
  homepage "https://github.com/wdm0006/vanity"
  version "0.2.0"
  license "MIT"

  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wdm0006/vanity/releases/download/v0.2.0/vanity_0.2.0_darwin_amd64.tar.gz"
      sha256 "c632428b500612fbed083ca7c7865ec432d3a18203987d733f1a9ca72cfb25f5"

      def install
        bin.install "vanity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wdm0006/vanity/releases/download/v0.2.0/vanity_0.2.0_darwin_arm64.tar.gz"
      sha256 "86468f341133a5851a1afdb5a815acf1aa30310369ee66198e6b79a44efece52"

      def install
        bin.install "vanity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wdm0006/vanity/releases/download/v0.2.0/vanity_0.2.0_linux_amd64.tar.gz"
      sha256 "ff574b81e6ba4703542f77e015678be60e6eecb82b8f9eb3c0ddd70dddba0092"
      def install
        bin.install "vanity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wdm0006/vanity/releases/download/v0.2.0/vanity_0.2.0_linux_arm64.tar.gz"
      sha256 "c670230e46e77dafe9f3d81060063398c6adeb304bbd3636802bf4fd9d443a73"
      def install
        bin.install "vanity"
      end
    end
  end

  test do
    system "#{bin}/vanity", "--help"
  end
end
